Repository Jusicool-Ver-2-0/Jusicool-Android, pull requests merged in 2025-07, with the labels that each got.

#159 🔀 :: (#158) - 차트 화면에서 비정상적으로 커지던 리스트 인덱스를 수정하였습니다,
  data/network/src/main/java/com/jusicool/network/di/NetworkModule.kt
  feature/chart/src/main/java/com/jusicool/chart/component/CandleChart.kt
Labels: 🐞 BugFix

#177 🔀 :: (#172) - 커뮤니티 글 작성 컴포넌트를 퍼블리싱 하였습니다
  app/build.gradle.kts
  app/src/main/java/com/jusicool/jusicool_android/navigation/JusicoolNavHost.kt
  feature/chart/src/main/java/com/jusicool/chart/navigation/ChartNavigation.kt
  feature/chart/src/main/java/com/jusicool/chart/view/ChartScreen.kt
  feature/community/src/main/java/com/meister/community/navigation/WriteDetailNavigation.kt
  feature/community/src/main/java/com/meister/community/view/WritePostRoute.kt
  ui/design-system/src/main/java/com/jusicool/design_system/icon/JusicoolIcon.kt
  ui/design-system/src/main/res/drawable/lucide_pencil_line.xml
Labels: ✨ Feature

#180 🔀 :: (#173) - 커뮤니티 글 작성 api를 연결하였습니다
  data/di/src/main/java/com/jusicool/di/RepositoryModule.kt
  data/model/src/main/java/com/jusicool/model/community/WritePostRequest.kt
  data/model/src/main/java/com/jusicool/model/mapper/community/WritePostMapper.kt
  data/network/src/main/java/com/jusicool/network/api/CommunityApi.kt
  data/network/src/main/java/com/jusicool/network/datasource/community/CommunityDataSource.kt
  data/network/src/main/java/com/jusicool/network/datasource/community/CommunityDataSourceImpl.kt
  data/network/src/main/java/com/jusicool/network/di/NetworkModule.kt
  data/network/src/main/java/com/jusicool/network/di/RemoteDataSourceModule.kt
  data/repository/src/main/java/com/jusicool/repository/CommunityRepositoryImpl.kt
  domain/entity/src/main/java/com/jusicool/entity/community/WritePostModel.kt
  domain/repository/src/main/java/com/jusicool/repository/CommunityRepository.kt
  domain/usecase/src/main/java/com/jusicool/usecase/community/PostWriteUseCase.kt
  feature/chart/src/main/java/com/jusicool/chart/navigation/ChartNavigation.kt
  feature/chart/src/main/java/com/jusicool/chart/view/ChartScreen.kt
  feature/community/build.gradle.kts
  feature/community/src/main/java/com/meister/community/navigation/WritePostNavigation.kt
  feature/community/src/main/java/com/meister/community/view/WritePostRoute.kt
  feature/community/src/main/java/com/meister/community/viewModel/WritePostViewModel.kt
Labels: ✨ Feature

#178 🔀 :: (#150) - chart list api connaction
  app/src/main/java/com/jusicool/jusicool_android/navigation/JusicoolNavHost.kt
  data/di/src/main/java/com/jusicool/di/RepositoryModule.kt
  data/model/src/main/java/com/jusicool/model/mapper/koreaInvestment/StockPriceResponseMapper.kt
  data/model/src/main/java/com/jusicool/model/mapper/koreaInvestment/StockPriceSummaryMapper.kt
  data/model/src/main/java/com/jusicool/model/mapper/market/MarketListResponseMapper.kt
  data/model/src/main/java/com/jusicool/model/market/MarketListResponse.kt
  data/network/src/main/java/com/jusicool/network/api/MarketApi.kt
  data/network/src/main/java/com/jusicool/network/api/OrderApi.kt
  data/network/src/main/java/com/jusicool/network/datasource/market/MarketDataSource.kt
  data/network/src/main/java/com/jusicool/network/datasource/market/MarketDataSourceImpl.kt
  data/network/src/main/java/com/jusicool/network/di/NetworkModule.kt
  data/network/src/main/java/com/jusicool/network/di/RemoteDataSourceModule.kt
  data/repository/src/main/java/com/jusicool/repository/KoreaInvestmentRepositoryImpl.kt
  data/repository/src/main/java/com/jusicool/repository/MarketRepositoryImpl.kt
  data/repository/src/main/java/com/jusicool/repository/WsKoreaInvestmentRepositoryImpl.kt
  domain/entity/src/main/java/com/jusicool/entity/koreaInvestment/AssetsCurrentPrice.kt
  domain/entity/src/main/java/com/jusicool/entity/market/RecommendMarketWithPrice.kt
  domain/repository/src/main/java/com/jusicool/repository/KoreaInvestmentRepository.kt
  domain/repository/src/main/java/com/jusicool/repository/MarketRepository.kt
  domain/repository/src/main/java/com/jusicool/repository/WsKoreaInvestmentRepository.kt
  domain/usecase/src/main/java/com/jusicool/usecase/holding/GetHoldingWithCurrentPriceUseCase.kt
  domain/usecase/src/main/java/com/jusicool/usecase/koreaInvestment/GetCurrentStockPriceUseCase.kt
  domain/usecase/src/main/java/com/jusicool/usecase/koreaInvestment/ObserveRealtimeStockPriceUseCase.kt
  domain/usecase/src/main/java/com/jusicool/usecase/market/GetCryptoRecommendMarketListUseCase.kt
  domain/usecase/src/main/java/com/jusicool/usecase/market/GetStockRecommendMarketListUseCase.kt
  domain/usecase/src/main/java/com/jusicool/usecase/market/GetTotalRecommendMarketListUseCase.kt
  domain/utils/src/main/java/com/jusicool/utils/Validators.kt
  feature/account/src/main/java/com/jusicool/account/view/AccountScreen.kt
  feature/investmentSearch/src/main/java/com/meister/investmentsearch/navigation/Navigation.kt
  feature/investmentSearch/src/main/java/com/meister/investmentsearch/view/ChartListRoute.kt
  feature/investmentSearch/src/main/java/com/meister/investmentsearch/view/InvestmentSearchRoute.kt
  feature/investmentSearch/src/main/java/com/meister/investmentsearch/viewModel/ChartListUiState.kt
  feature/investmentSearch/src/main/java/com/meister/investmentsearch/viewModel/ChartListViewModel.kt
Labels: ✨ Feature

#186 🔀 :: (#185) - assets list paging setting
  data/model/src/main/java/com/jusicool/model/mapper/market/MarketListResponseMapper.kt
  data/model/src/main/java/com/jusicool/model/market/MarketListResponse.kt
  data/model/src/main/java/com/jusicool/model/market/MarketResponse.kt
  data/network/src/main/java/com/jusicool/network/api/MarketApi.kt
  data/network/src/main/java/com/jusicool/network/datasource/market/MarketDataSource.kt
  data/network/src/main/java/com/jusicool/network/datasource/market/MarketDataSourceImpl.kt
  data/repository/build.gradle.kts
  data/repository/src/main/java/com/jusicool/repository/KoreaInvestmentRepositoryImpl.kt
  data/repository/src/main/java/com/jusicool/repository/MarketRepositoryImpl.kt
  data/repository/src/main/java/com/jusicool/repository/paging/MarketListPagingSource.kt
  domain/repository/build.gradle.kts
  domain/repository/src/main/java/com/jusicool/repository/KoreaInvestmentRepository.kt
  domain/repository/src/main/java/com/jusicool/repository/MarketRepository.kt
  domain/usecase/build.gradle.kts
  domain/usecase/src/main/java/com/jusicool/usecase/koreaInvestment/GetCurrentStockPriceUseCase.kt
  domain/usecase/src/main/java/com/jusicool/usecase/market/GetCryptoRecommendMarketListUseCase.kt
  domain/usecase/src/main/java/com/jusicool/usecase/market/GetRecommendMarketPagingUseCase.kt
  domain/usecase/src/main/java/com/jusicool/usecase/market/GetStockRecommendMarketListUseCase.kt
  domain/usecase/src/main/java/com/jusicool/usecase/market/GetTotalRecommendMarketListUseCase.kt
  domain/usecase/src/main/java/com/jusicool/usecase/market/util/mergeWithPrices.kt
  feature/investmentSearch/src/main/java/com/meister/investmentsearch/viewModel/ChartListViewModel.kt
  gradle/libs.versions.toml
Labels: ✨ Feature

#190 :sparkles: :: Logger 클래스의 로깅 함수들이 자동으로 stacktrace hfer를 띄우도록 로직 추가
  ui/utils/src/main/java/com/jusicool/utils/Logger.kt
Labels: ♻️ Refactor
