Repository Jusicool-Ver-2-0/Jusicool-Android, pull requests merged in 2025-04, with the labels that each got.

#25 🔀 :: (#22) - setting module structure
  data/.gitignore
  domain/.gitignore
  feature/.gitignore
  settings.gradle.kts
  ui/.gitignore
Labels: ⚙ Setting

#64 🔀 :: (#44) - Theme, Color, Typography 만들었습니다.
  gradle/libs.versions.toml
  ui/design-system/build.gradle.kts
  ui/design-system/src/main/java/com/jusicool/design_system/theme/.gitkeep
  ui/design-system/src/main/java/com/jusicool/design_system/theme/JusicoolTheme.kt
  ui/design-system/src/main/java/com/jusicool/design_system/theme/JusicoolTypography.kt
  ui/design-system/src/main/java/com/jusicool/design_system/theme/color/ColorTheme.kt
  ui/design-system/src/main/java/com/jusicool/design_system/theme/color/JusicoolColor.kt
  ui/design-system/src/main/res/font/pretendard_black.otf
  ui/design-system/src/main/res/font/pretendard_bold.otf
  ui/design-system/src/main/res/font/pretendard_extrabold.otf
  ui/design-system/src/main/res/font/pretendard_extralight.otf
  ui/design-system/src/main/res/font/pretendard_light.otf
  ui/design-system/src/main/res/font/pretendard_medium.otf
  ui/design-system/src/main/res/font/pretendard_regular.otf
  ui/design-system/src/main/res/font/pretendard_semibold.otf
  ui/design-system/src/main/res/font/pretendard_thin.otf
Labels: ⚙ Setting

#66 🔀 :: (#65) - ui module setting
  data/di/.gitignore
  data/di/build.gradle.kts
  data/di/src/androidTest/java/com/jusicool/di/ExampleInstrumentedTest.kt
  data/di/src/main/AndroidManifest.xml
  data/di/src/main/java/com/jusicool/di/RepositoryModule.kt
  data/di/src/test/java/com/jusicool/di/ExampleUnitTest.kt
  data/local/.gitignore
  data/local/build.gradle.kts
  data/local/src/androidTest/java/com/jusicool/local/ExampleInstrumentedTest.kt
  data/local/src/main/AndroidManifest.xml
  data/local/src/main/java/com/jusicool/local/.gitkeep
  data/local/src/test/java/com/jusicool/local/ExampleUnitTest.kt
  data/model/.gitignore
  data/model/build.gradle.kts
  data/model/src/androidTest/java/com/jusicool/model/ExampleInstrumentedTest.kt
  data/model/src/main/AndroidManifest.xml
  data/model/src/main/java/com/jusicool/model/.gitkeep
  data/model/src/test/java/com/jusicool/model/ExampleUnitTest.kt
  data/network/build.gradle.kts
  data/repository/.gitignore
  data/repository/build.gradle.kts
  data/repository/src/androidTest/java/com/jusicool/repository/ExampleInstrumentedTest.kt
  data/repository/src/main/AndroidManifest.xml
  data/repository/src/main/java/com/jusicool/repository/.gitkeep
  data/repository/src/test/java/com/jusicool/repository/ExampleUnitTest.kt
  data/utils/.gitignore
  data/utils/build.gradle.kts
  data/utils/src/androidTest/java/com/jusicool/utils/ExampleInstrumentedTest.kt
  data/utils/src/main/AndroidManifest.xml
  data/utils/src/main/java/com/jusicool/utils/.gitkeep
  data/utils/src/test/java/com/jusicool/utils/ExampleUnitTest.kt
  settings.gradle.kts
Labels: ⚙ Setting

#70 🔀 :: (#67) - domain module setting
  domain/entity/.gitignore
  domain/entity/build.gradle.kts
  domain/entity/src/main/AndroidManifest.xml
  domain/entity/src/main/java/com/jusicool/entity/.gitkeep
  domain/repository/.gitignore
  domain/repository/build.gradle.kts
  domain/repository/src/main/AndroidManifest.xml
  domain/repository/src/main/java/com/jusicool/repository/.gitkeep
  domain/usecase/.gitignore
  domain/usecase/build.gradle.kts
  domain/usecase/src/main/AndroidManifest.xml
  domain/usecase/src/main/java/com/jusicool/usecase/.gitkeep
  domain/utils/.gitignore
  domain/utils/build.gradle.kts
  domain/utils/src/main/AndroidManifest.xml
  domain/utils/src/main/java/com/jusicool/utils/.gitkeep
  settings.gradle.kts
Labels: ⚙ Setting

#72 🔀 :: (#71) - create textField component
  gradle/libs.versions.toml
  ui/design-system/build.gradle.kts
  ui/design-system/src/main/java/com/jusicool/design_system/component/.gitkeep
  ui/design-system/src/main/java/com/jusicool/design_system/component/textField/JusicoolTextField.kt
  ui/design-system/src/main/java/com/jusicool/design_system/theme/JusicoolTheme.kt
  ui/design-system/src/main/java/com/jusicool/design_system/theme/color/ColorTheme.kt
  ui/design-system/src/main/java/com/jusicool/design_system/theme/color/JusicoolColor.kt
Labels: ✨ Feature

#74 :twisted_rightwards_arrows: :: (#72) - add icon & 컴포넌트화
  gradle/libs.versions.toml
  ui/design-system/build.gradle.kts
  ui/design-system/src/main/java/com/jusicool/design_system/icon/.gitkeep
  ui/design-system/src/main/java/com/jusicool/design_system/icon/JusicoolIcon.kt
  ui/design-system/src/main/res/drawable/account.xml
  ui/design-system/src/main/res/drawable/chart_line.xml
  ui/design-system/src/main/res/drawable/clarity_arrow_line.xml
  ui/design-system/src/main/res/drawable/flat_cylinder_3.xml
  ui/design-system/src/main/res/drawable/lets_icons_setting_fill.xml
  ui/design-system/src/main/res/drawable/material_symbols_news_outline.xml
  ui/design-system/src/main/res/drawable/pie_chartfilled.xml
  ui/design-system/src/main/res/drawable/right_arrow.xml
  ui/design-system/src/main/res/drawable/search.xml
  ui/design-system/src/main/res/drawable/union.xml
  ui/design-system/src/main/res/values/strings.xml
Labels: ✨ Feature

#76 🔀 :: (#73) - create button
  ui/design-system/src/main/java/com/jusicool/design_system/component/button/JusicoolButton.kt
  ui/design-system/src/main/java/com/jusicool/design_system/component/button/state/ButtonState.kt
  ui/design-system/src/main/java/com/jusicool/design_system/component/modifier/JusicoolClickable.kt
  ui/design-system/src/main/java/com/jusicool/design_system/component/modifier/MultipleEventsCutter.kt
Labels: ✨ Feature

#82 🔀 :: (#81) - domain 모듈 안 파일들에 공통 플러그인 적용하였습니다
  domain/entity/build.gradle.kts
  domain/repository/build.gradle.kts
  domain/usecase/build.gradle.kts
  domain/utils/build.gradle.kts
Labels: ⚙ Setting

#87 🔀 :: (#77) - 차트 화면을 퍼블리싱했습니다
  app/src/main/AndroidManifest.xml
  build-logic/convention/src/main/java/AndroidFeatureConventionPlugin.kt
  build-logic/convention/src/main/java/AndroidHiltConventionPlugin.kt
  data/model/src/main/java/com/jusicool/model/chart/CandleChartModel.kt
  data/model/src/main/java/com/jusicool/model/chart/ChartInformationModel.kt
  data/model/src/main/java/com/jusicool/model/chart/ChartPriceModel.kt
  data/model/src/main/java/com/jusicool/model/community/CommunityModel.kt
  data/model/src/main/java/com/jusicool/model/news/NewsModel.kt
  feature/chart/build.gradle.kts
  feature/chart/consumer-rules.pro
  feature/chart/proguard-rules.pro
  feature/chart/src/main/AndroidManifest.xml
  feature/chart/src/main/java/com/jusicool/chart/component/CandleChart.kt
  feature/chart/src/main/java/com/jusicool/chart/component/CandleStick.kt
  feature/chart/src/main/java/com/jusicool/chart/component/CommunityCard.kt
  feature/chart/src/main/java/com/jusicool/chart/component/NewsCard.kt
  feature/chart/src/main/java/com/jusicool/chart/component/PriceBarChart.kt
  feature/chart/src/main/java/com/jusicool/chart/view/ChartScreen.kt
  gradle/libs.versions.toml
  settings.gradle.kts
  ui/design-system/build.gradle.kts
  ui/design-system/src/main/java/com/jusicool/design_system/component/button/JusicoolButton.kt
  ui/design-system/src/main/java/com/jusicool/design_system/icon/JusicoolIcon.kt
  ui/design-system/src/main/java/com/jusicool/design_system/theme/color/ColorTheme.kt
  ui/design-system/src/main/java/com/jusicool/design_system/theme/color/JusicoolColor.kt
  ui/design-system/src/main/res/drawable/comment.xml
  ui/design-system/src/main/res/drawable/heart.xml
  ui/design-system/src/main/res/values/strings.xml
Labels: ✨ Feature

#91 🔀 :: (#90) - 텍스트 필드에서 helpText랑 error텍스트가 거꾸로 되어 있던 것을 수정했습니다
  ui/design-system/src/main/java/com/jusicool/design_system/component/textField/JusicoolTextField.kt
Labels: 🐞 BugFix
